#!/bin/bash
docker exec --interactive --tty neo4j cypher-shell -u neo4j -p password "
MATCH (n) DETACH DELETE n;
CREATE (:Node {Id: 1});
CREATE (:Node {Id: 2});
CREATE (:Node {Id: 3});
CREATE (:Node {Id: 4});
CREATE (:Node {Id: 5});
CREATE (:Node {Id: 6});
CREATE (:Node {Id: 7});
CREATE (:Node {Id: 8});
CREATE (:Node {Id: 9});
CREATE (:Node {Id: 10});
CREATE (:Node {Id: 11});
CREATE (:Node {Id: 12});
CREATE (:Node {Id: 13});
CREATE (:Node {Id: 14});
CREATE (:Node {Id: 15});
CREATE (:Node {Id: 16});
CREATE (:Node {Id: 17});
CREATE (:Node {Id: 18});
CREATE (:Node {Id: 19});
CREATE (:Node {Id: 20});
CREATE (:Node {Id: 21});
CREATE (:Node {Id: 22});
CREATE (:Node {Id: 23});
CREATE (:Node {Id: 24});
CREATE (:Node {Id: 25});
CREATE (:Node {Id: 26});
CREATE (:Node {Id: 27});
CREATE (:Node {Id: 28});
CREATE (:Node {Id: 29});
CREATE (:Node {Id: 30});
CREATE (:Node {Id: 31});
CREATE (:Node {Id: 32});
CREATE (:Node {Id: 33});
MATCH (a:Node {Id: 15}), (b:Node {Id: 14}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 14}), (b:Node {Id: 13}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 13}), (b:Node {Id: 16}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 13}), (b:Node {Id: 10}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 16}), (b:Node {Id: 3}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 16}), (b:Node {Id: 18}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 18}), (b:Node {Id: 11}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 18}), (b:Node {Id: 5}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 3}), (b:Node {Id: 20}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 3}), (b:Node {Id: 7}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 14}), (b:Node {Id: 9}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 7}), (b:Node {Id: 4}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 5}), (b:Node {Id: 19}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 5}), (b:Node {Id: 8}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 20}), (b:Node {Id: 1}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 10}), (b:Node {Id: 6}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 7}), (b:Node {Id: 12}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 1}), (b:Node {Id: 17}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 8}), (b:Node {Id: 2}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 8}), (b:Node {Id: 14}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 3}), (b:Node {Id: 1}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 9}), (b:Node {Id: 7}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 7}), (b:Node {Id: 6}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 19}), (b:Node {Id: 1}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 8}), (b:Node {Id: 3}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 5}), (b:Node {Id: 11}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 2}), (b:Node {Id: 4}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 20}), (b:Node {Id: 6}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 4}), (b:Node {Id: 15}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 8}), (b:Node {Id: 7}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 13}), (b:Node {Id: 11}) MERGE (a)-[:CONNECTED]->(b);
MATCH (a:Node {Id: 8}), (b:Node {Id: 18}) MERGE (a)-[:CONNECTED]->(b);
"
